# Generated by Django 4.2.17 on 2025-01-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package',
            field=models.CharField(choices=[('Through Hole', 'Through Hole'), ('Surface Mount', 'Surface Mount'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Batteries', 'Batteries'), ('Battery Casing & Holder', 'Battery Casing & Holder'), ('Battery Charger/Modules', 'Battery Charger/Modules'), ('DC/DC Converter', '')], max_length=50, null=True),
        ),
    ]
