# Generated by Django 4.2.17 on 2025-01-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_location_product_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text to display in the marquee', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Batteries', 'Batteries'), ('Battery Casing & Holder', 'Battery Casing & Holder'), ('Battery Charger/Modules', 'Battery Charger/Modules'), ('DC/DC Converter', 'DC/DC Converter'), ('Capacitors', 'Capacitors'), ('Development Boards', 'Development Boards'), ('Diodes', 'Diodes'), ('Displays', 'Displays'), ('Fan', 'Fan'), ('IC (Digital/Logic)', 'IC (Digital/Logic)'), ('IC (Other)', 'IC (Other)'), ('Inductors', 'Inductors'), ('LEDs', 'LEDs'), ('Machining Bolts / Screws / Kits', 'Machining Bolts / Screws / Kits'), ('Misc.', 'Misc.'), ('Motors', 'Motors'), ('Optocoupler', 'Optocoupler'), ('Potentiometers', 'Potentiometers'), ('Power Supply', 'Power Supply'), ('Pumps', 'Pumps'), ('Relays', 'Relays'), ('Remotes', 'Remotes'), ('Resistors', 'Resistors'), ('Sensors', 'Sensors'), ('Speaker / Buzzer', 'Speaker / Buzzer'), ('Switches', 'Switches'), ('Transistors', 'Transistors'), ('Wireless RF/BT', 'Wireless RF/BT')], max_length=50, null=True),
        ),
    ]
