# Generated by Django 4.2.17 on 2025-01-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_marqueetext_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, choices=[('Batteries', 'Batteries'), ('Battery Casing & Holder', 'Battery Casing & Holder'), ('Battery Charger/Modules', 'Battery Charger/Modules'), ('DC/DC Converter', 'DC/DC Converter'), ('Capacitors', 'Capacitors'), ('Development Boards', 'Development Boards'), ('Diodes', 'Diodes'), ('Displays', 'Displays'), ('Fan', 'Fan'), ('IC (Digital/Logic)', 'IC (Digital/Logic)'), ('IC (Other)', 'IC (Other)'), ('Inductors', 'Inductors'), ('LEDs', 'LEDs'), ('Machining Bolts / Screws / Kits', 'Machining Bolts / Screws / Kits'), ('Misc.', 'Misc.'), ('Motors', 'Motors'), ('Optocoupler', 'Optocoupler'), ('Potentiometers', 'Potentiometers'), ('Power Supply', 'Power Supply'), ('Pumps', 'Pumps'), ('Relays', 'Relays'), ('Remotes', 'Remotes'), ('Resistors', 'Resistors'), ('Sensors', 'Sensors'), ('Speaker / Buzzer', 'Speaker / Buzzer'), ('Switches', 'Switches'), ('Transistors', 'Transistors'), ('Wireless RF/BT', 'Wireless RF/BT')], max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
