# Generated by Django 4.2.17 on 2025-01-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_customorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorderitem',
            name='category',
            field=models.CharField(blank=True, choices=[('Batteries', 'Batteries'), ('Battery Casing & Holder', 'Battery Casing & Holder'), ('Battery Charger/Modules', 'Battery Charger/Modules'), ('Cables', 'Cables'), ('Capacitors', 'Capacitors'), ('Connectors', 'Connectors'), ('Consumables', 'Consumables'), ('DC/DC Converter', 'DC/DC Converter'), ('Development Boards', 'Development Boards'), ('Diodes', 'Diodes'), ('Displays', 'Displays'), ('Fan', 'Fan'), ('Fuse', 'Fuse'), ('Hardware, Fasteners, Accessories', 'Hardware, Fasteners, Accessories'), ('IC (Digital/Logic)', 'IC (Digital/Logic)'), ('IC (Other)', 'IC (Other)'), ('Inductors', 'Inductors'), ('LEDs', 'LEDs'), ('Magnetics', 'Magnetics'), ('Misc.', 'Misc.'), ('Motors', 'Motors'), ('Optoelectronics', 'Optoelectronics'), ('Optocoupler/Optoisolator', 'Optocoupler/Optoisolator'), ('Potentiometers', 'Potentiometers'), ('Power Supply', 'Power Supply'), ('Pumps', 'Pumps'), ('Relays', 'Relays'), ('Remotes', 'Remotes'), ('Resistors', 'Resistors'), ('Sensors', 'Sensors'), ('Speaker / Buzzer', 'Speaker / Buzzer'), ('Switches', 'Switches'), ('Transformers', 'Transformers'), ('Transistors', 'Transistors'), ('Wire', 'Wire'), ('Wireless RF/BT', 'Wireless RF/BT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Batteries', 'Batteries'), ('Battery Casing & Holder', 'Battery Casing & Holder'), ('Battery Charger/Modules', 'Battery Charger/Modules'), ('Cables', 'Cables'), ('Capacitors', 'Capacitors'), ('Connectors', 'Connectors'), ('Consumables', 'Consumables'), ('DC/DC Converter', 'DC/DC Converter'), ('Development Boards', 'Development Boards'), ('Diodes', 'Diodes'), ('Displays', 'Displays'), ('Fan', 'Fan'), ('Fuse', 'Fuse'), ('Hardware, Fasteners, Accessories', 'Hardware, Fasteners, Accessories'), ('IC (Digital/Logic)', 'IC (Digital/Logic)'), ('IC (Other)', 'IC (Other)'), ('Inductors', 'Inductors'), ('LEDs', 'LEDs'), ('Magnetics', 'Magnetics'), ('Misc.', 'Misc.'), ('Motors', 'Motors'), ('Optoelectronics', 'Optoelectronics'), ('Optocoupler/Optoisolator', 'Optocoupler/Optoisolator'), ('Potentiometers', 'Potentiometers'), ('Power Supply', 'Power Supply'), ('Pumps', 'Pumps'), ('Relays', 'Relays'), ('Remotes', 'Remotes'), ('Resistors', 'Resistors'), ('Sensors', 'Sensors'), ('Speaker / Buzzer', 'Speaker / Buzzer'), ('Switches', 'Switches'), ('Transformers', 'Transformers'), ('Transistors', 'Transistors'), ('Wire', 'Wire'), ('Wireless RF/BT', 'Wireless RF/BT')], max_length=50, null=True),
        ),
    ]
