# Generated by Django 4.2.17 on 2025-01-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_customorderitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorderitem',
            name='category',
            field=models.CharField(blank=True, choices=[('Batteries', 'Batteries'), ('Cables', 'Cables'), ('Capacitors', 'Capacitors'), ('Connectors', 'Connectors'), ('Consumables', 'Consumables'), ('DC/DC Converter', 'DC/DC Converter'), ('Development Boards', 'Development Boards'), ('Diodes', 'Diodes'), ('Displays', 'Displays'), ('Equipment', 'Equipment'), ('Fan', 'Fan'), ('Fuse', 'Fuse'), ('Hardware, Fasteners, Accessories', 'Hardware, Fasteners, Accessories'), ('IC (Digital/Logic)', 'IC (Digital/Logic)'), ('IC (Other)', 'IC (Other)'), ('Inductors', 'Inductors'), ('LEDs', 'LEDs'), ('Magnetics', 'Magnetics'), ('Misc.', 'Misc.'), ('Motors', 'Motors'), ('Optoelectronics', 'Optoelectronics'), ('Optocoupler/Optoisolator', 'Optocoupler/Optoisolator'), ('Pumps', 'Pumps'), ('Relays', 'Relays'), ('Remotes', 'Remotes'), ('Resistors', 'Resistors'), ('Sensors', 'Sensors'), ('Speaker / Buzzer', 'Speaker / Buzzer'), ('Switches', 'Switches'), ('Transformers', 'Transformers'), ('Transistors', 'Transistors'), ('Wire', 'Wire'), ('Wireless RF/BT', 'Wireless RF/BT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Batteries', 'Batteries'), ('Cables', 'Cables'), ('Capacitors', 'Capacitors'), ('Connectors', 'Connectors'), ('Consumables', 'Consumables'), ('DC/DC Converter', 'DC/DC Converter'), ('Development Boards', 'Development Boards'), ('Diodes', 'Diodes'), ('Displays', 'Displays'), ('Equipment', 'Equipment'), ('Fan', 'Fan'), ('Fuse', 'Fuse'), ('Hardware, Fasteners, Accessories', 'Hardware, Fasteners, Accessories'), ('IC (Digital/Logic)', 'IC (Digital/Logic)'), ('IC (Other)', 'IC (Other)'), ('Inductors', 'Inductors'), ('LEDs', 'LEDs'), ('Magnetics', 'Magnetics'), ('Misc.', 'Misc.'), ('Motors', 'Motors'), ('Optoelectronics', 'Optoelectronics'), ('Optocoupler/Optoisolator', 'Optocoupler/Optoisolator'), ('Pumps', 'Pumps'), ('Relays', 'Relays'), ('Remotes', 'Remotes'), ('Resistors', 'Resistors'), ('Sensors', 'Sensors'), ('Speaker / Buzzer', 'Speaker / Buzzer'), ('Switches', 'Switches'), ('Transformers', 'Transformers'), ('Transistors', 'Transistors'), ('Wire', 'Wire'), ('Wireless RF/BT', 'Wireless RF/BT')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('equipment', models.ForeignKey(limit_choices_to={'category': 'Equipment'}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
    ]
