# Generated by Django 4.2.17 on 2025-01-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorderitem',
            name='package',
            field=models.CharField(choices=[('Through Hole', 'Through Hole'), ('Surface Mount', 'Surface Mount'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
